### ISSUE TITLE
Unresolved dependencies when build with maven after cloning project

### ISSUE THREAD

**Issue by mironuk** [uniVocity/univocity-trader#115] opened 2020-12-15 16:47 UTC
I get the following maven message:

[ERROR] Failed to execute goal on project univocity-trader-examples: Could not resolve dependencies for project com.univocity:univocity-trader-examples:jar:1.0.0-SNAPSHOT: Failure to find com.univocity:univocity-trader-interactivebrokers:jar:1.0.0-SNAPSHOT in https://dl.bintray.com/testng-team/testng/ was cached in the local repository, resolution will not be reattempted until the update interval of testng has elapsed or updates are forced -> [Help 1]

**Comment by jbax** [comment] 2020-12-15 17:03
Duplicate of https://github.com/uniVocity/univocity-trader/issues/48

**Closed by jbax** 2020-12-15 17:03 UTC
